# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0" # Want to make your mod open source? Check out https://choosealicense.com/!

issueTrackerURL = "https://github.com/sudolev/CreateInteriorsMod/issues"

[[mods]]
modId = "escalators"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "Create: Escalators"
displayURL = "https://sudolev.github.io/EscalatorsMod/"
issueTrackerURL = "https://github.com/sudolev/CreateInteriorsMod/issues"
logoFile="mod_banner.png"
credits = ""
authors = "sudolev"
description = '''

'''

# An (optional) dependency for your mod. Though technically not required,
# it's always helpful to add these to stop your mod from loading when something is missing
# rather than erroring out later
[[dependencies.escalators]]
modId = "forge"
mandatory = true # do you **need** this mod to be able to launch?
# A version range using interval notation.
# Brackets mean "inclusive" bounds, while parentheses mean "exclusive".
versionRange = "[47,)" # This essentially means any forge >= 47
ordering = "NONE" # Use this if you want your mod to be loaded specifically BEFORE or AFTER another mod
side = "BOTH" # Specify where this mod is required: can be BOTH, CLIENT or SERVER

[[dependencies.escalators]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.escalators]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.e-22,)"
ordering = "NONE"
side = "BOTH"

[modproperties.interiors]
catalogueImageIcon="icon.png"
catalogueBackground="mod_banner.png"
configuredBackground="create:textures/block/seat/top_red.png"